[package]
name = "ref-type"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", default-features = false, features = ["derive", "std"] }
regex = "1.9.3"
